### PR TITLE
[WIP] update-devops-pipelines

### PR DESCRIPTION
**Pull request by pasqualedevita**

### CODE REVIEW

**Comment by Undermaken** [comment]
@pasqualedevita is this PR still valid?

**Comment by pasqualedevita** [comment]
> @pasqualedevita is this PR still valid?

yes but a work-in-progess

**Comment by Undermaken** [comment]
@pasqualedevita is this PR still valid? 🙄

**Comment by Undermaken** [comment]
Since this PR is about 10 month old, I'm closing it.
It could be re-opened at any time from the closed PR list

**Pull request closed without merging**
