### PR TITLE
[IA-303] Incident

### PR DESCRIPTION
**Pull request by mariateresaventura**
copy for maintenance banners

### CODE REVIEW

**Comment by Undermaken** [comment]
@mariateresaventura @thisisjp 
Is this PR obsolete?

**Comment by thisisjp** [comment]
@Undermaken this content was prepared in case of emergency during scheduled maintenance (last week).
Let's keep it in draft, it's going to be useful when in case 🤞

**Comment by Undermaken** [comment]
Ok. Anyway I leave my warning: if your goal is to have a content _ready-to-use_ in emergencies, you should keep it updated.
This content changes continuously and you'll often have version conflicts, as in this case 
Schermata 2021-11-02 alle 15 13 18

So when you'll try to use it, you'll resolve conflicts before and maybe it'll take more time than make if from scratch.

**Comment by thisisjp** [comment]
You can also close it, but we need a space to store this content, as we don't have a proper tool yet—and this draft is the best we can have right now ¯\_(ツ)_/¯

**Pull request closed without merging**
