### PR TITLE
GDO logos

### PR DESCRIPTION
**Pull request by thisisjp**
This PR adds logos for GDO cards:

- Esselunga
- Conad
- Unicoop Firenze

### CODE REVIEW

**Comment by fabriziofff** [comment]
@thisisjp in order to display a different logo for the `GDO` and the `loyalty` I propose the following structure:

`logos/privative/gdo/ID.png` -> GDO logo
`logos/privative/loyalty/ID.png` -> Loyalty logo

In this way we can have a different representation, based on the same ID.

(cc @debiff )

**Comment by thisisjp** [comment]
@debiff @fabriziofff I'll get back to you as soon as I'll receive feedback from the different GDOs

**Comment by fabriziofff** [comment]
@thisisjp I'm going to merge this PR in order to use the data for the test. I've created a story https://www.pivotaltracker.com/story/show/177245931 to track the activity of adding missing logos for loyalty programs.

**Review by fabriziofff — APPROVED** [review]

**Comment by thisisjp** [comment]
@fabriziofff in any case these logos are okay for the first screen

**Pull request merged**
