### PR TITLE
[IOPID-1739] change CDN urls 

### PR DESCRIPTION
**Pull request by Ladirico**
## Short description
Change CDN urls from assets.cdn.io.italia.it to assets.cdn.io.pagopa.it for all occurrence

## How to test
Verify that each link works identically to the as-is

### CODE REVIEW

**Comment by CrisTofani** [comment]
@Ladirico isn't this a duplicate of #778?

**Review by Vangaorth — APPROVED** [review]
LGTM for the UA's section

**Comment by Ladirico** [comment]
> @Ladirico isn't this a duplicate of #778?

Yes, sorry! I hadn't seen the open PR.
What do you say? Should I close this one?

cc: @CrisTofani

**Comment by CrisTofani** [comment]
no problem we can close the other 😄

**Review by CrisTofani — APPROVED** [review]

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Review by Hantex9 — APPROVED** [review]
LGTM

**Pull request merged**
